### ISSUE TITLE
Make cdp4-services-dal handle copy operation

### ISSUE THREAD

**Issue by IevhenIkonnykov** [RHEAGROUP/CDP4-SDKTs-Community-Edition#14]
Currently copy is not supported by cdp4-services-dal, but it should, because it is supported in C# and Java implementations.

**Comment by samatrhea** [comment]
it should not be supported there, since the cdp4-services-dal lets the server handle copies.

**Comment by samatrhea** [comment]
@alexatrhea and @IevhenIkonnykov : in my opinion there is nothing to fix. The cdp4servicesdal is different from the wspservicesdal because the copy operation it uses is the one that is handled on the server. This DAL should NOT implement it client side.

**Comment by IevhenIkonnykov** [comment]
@samatrhea and @alexatrhea  I should have added more context to this issue. Looking at it again I see that you are right. The only thing I would like to mention is that C# SDK and Java SDK have CopyOperationHandler class that is not used anywhere in SDK. Is it correct? Is it used on the server side? Probably I was talking about this class.

**Comment by samatrhea** [comment]
The CDP4 Service only make use of the `CDP4Common` and `CDP4JsonSerialzer` libraries. So no, the server does not depend on the that class. My opinion is we remove it from CDP4ServicesDal (as well as the corresponding test fixture)

**Comment by IevhenIkonnykov** [comment]
This issue is no longer valid. I close it.
