### ISSUE TITLE
Move code generation from T4 to dotLiquid

### ISSUE THREAD

**Issue by IevhenIkonnykov** [RHEAGROUP/CDP4-SDKTs-Community-Edition#20]
Currently all generated code was produced by T4 code generator, but C# SDK and Java SDK have moved to dotLiquid. It would be beneficial to have only one (dotLiquid) code generator for all SDKs.

**Comment by samatrhea** [comment]
@IevhenIkonnykov i agree, it should all be part of the C# one, from which we also generate SQL etc.

**Comment by IevhenIkonnykov** [comment]
Resolved and hosted in the appropriate place.
